import type { ERPData } from '@/lib/erp/types'

function isoNow() {
  return new Date().toISOString()
}

function shiftDays(days: number) {
  const value = new Date()
  value.setDate(value.getDate() + days)
  return value.toISOString()
}

export function createDefaultERPData(): ERPData {
  const seededAt = isoNow()

  return {
    permissions: {
      view_dashboard: {
        id: 'view_dashboard',
        label: 'View dashboard',
        description: 'See daily ERP analytics and operational highlights.',
      },
      view_products: {
        id: 'view_products',
        label: 'View inventory',
        description: 'Read product, warehouse, and supplier stock information.',
      },
      manage_products: {
        id: 'manage_products',
        label: 'Manage inventory',
        description: 'Create products and record warehouse purchases.',
      },
      manage_orders: {
        id: 'manage_orders',
        label: 'Manage orders',
        description: 'Create sales orders and update fulfillment state.',
      },
      view_reports: {
        id: 'view_reports',
        label: 'View reports',
        description: 'Access sales, stock, and user performance reports.',
      },
      view_finance: {
        id: 'view_finance',
        label: 'View finance',
        description: 'See payment, due, profit, and expense related numbers.',
      },
    },
    roles: {
      admin: {
        id: 'admin',
        name: 'Admin',
        description: 'Full ERP access.',
        permissions: [
          'view_dashboard',
          'view_products',
          'manage_products',
          'manage_orders',
          'view_reports',
          'view_finance',
        ],
      },
      store_manager: {
        id: 'store_manager',
        name: 'Store Manager',
        description: 'Handles stock, warehouse, and replenishment operations.',
        permissions: [
          'view_dashboard',
          'view_products',
          'manage_products',
          'view_reports',
        ],
      },
      sales_person: {
        id: 'sales_person',
        name: 'Sales Person',
        description: 'Creates orders and follows customer delivery.',
        permissions: ['view_dashboard', 'view_products', 'manage_orders', 'view_reports'],
      },
      accountant: {
        id: 'accountant',
        name: 'Accountant',
        description: 'Tracks revenue, dues, and margin.',
        permissions: ['view_dashboard', 'view_reports', 'view_finance'],
      },
      viewer: {
        id: 'viewer',
        name: 'Viewer',
        description: 'Read-only workspace access.',
        permissions: ['view_dashboard', 'view_products', 'view_reports'],
      },
    },
    users: {
      u_admin: {
        id: 'u_admin',
        name: 'Muaz',
        loginId: 'muazbd@technology',
        email: 'muazbd@technology@local',
        phone: '01844902338',
        password: 'muaz@123#',
        roleId: 'admin',
        title: 'Operations Director',
        status: 'active',
      },
      u_store: {
        id: 'u_store',
        name: 'Farzana Akter',
        loginId: 'farzana',
        email: 'farzana@muazbd.com',
        phone: '+8801700000002',
        password: '123456',
        roleId: 'store_manager',
        title: 'Store Manager',
        status: 'active',
      },
      u_sales: {
        id: 'u_sales',
        name: 'Sabbir Ahmed',
        loginId: 'sabbir',
        email: 'sabbir@muazbd.com',
        phone: '+8801700000003',
        password: '123456',
        roleId: 'sales_person',
        title: 'Sales Executive',
        status: 'active',
      },
      u_accounts: {
        id: 'u_accounts',
        name: 'Nabila Islam',
        loginId: 'nabila',
        email: 'nabila@muazbd.com',
        phone: '+8801700000004',
        password: '123456',
        roleId: 'accountant',
        title: 'Accounts Officer',
        status: 'active',
      },
      u_viewer: {
        id: 'u_viewer',
        name: 'Jitu Roy',
        loginId: 'jitu',
        email: 'jitu@muazbd.com',
        phone: '+8801700000005',
        password: '123456',
        roleId: 'viewer',
        title: 'Management Viewer',
        status: 'active',
      },
    },
    warehouses: {
      wh_dhaka: {
        id: 'wh_dhaka',
        name: 'Dhaka Main Warehouse',
        location: 'Mirpur, Dhaka',
      },
      wh_ctg: {
        id: 'wh_ctg',
        name: 'Chattogram Transit Hub',
        location: 'Agrabad, Chattogram',
      },
    },
    suppliers: {
      sup_alpha: {
        id: 'sup_alpha',
        name: 'Alpha Sourcing',
        company: 'Alpha Sourcing Ltd.',
        phone: '+8801800000001',
        email: 'imports@alphasourcing.com',
        location: 'Uttara, Dhaka',
        supplierType: 'foreign',
        country: 'China',
        lcNumber: 'LC-CN-24018',
        lcStatus: 'opened',
        productCost: 580000,
        shippingCost: 72000,
        customsDuty: 46500,
        otherCost: 15000,
        currency: 'BDT',
        notes: 'Winter collection shipment under LC.',
        createdAt: shiftDays(-55),
        updatedAt: shiftDays(-2),
      },
      sup_globe: {
        id: 'sup_globe',
        name: 'Globe Imports',
        company: 'Globe Imports',
        phone: '+8801800000002',
        email: 'ops@globeimports.com',
        location: 'Agrabad, Chattogram',
        supplierType: 'importer',
        country: 'Bangladesh',
        lcNumber: 'IMP-CTG-117',
        lcStatus: 'released',
        productCost: 420000,
        shippingCost: 38000,
        customsDuty: 31000,
        otherCost: 9000,
        currency: 'BDT',
        notes: 'Handles port release and local transport.',
        createdAt: shiftDays(-48),
        updatedAt: shiftDays(-1),
      },
      sup_textile: {
        id: 'sup_textile',
        name: 'Textile House',
        company: 'Textile House BD',
        phone: '+8801800000003',
        email: 'sales@textilehousebd.com',
        location: 'Narayanganj',
        supplierType: 'local',
        country: 'Bangladesh',
        lcNumber: '',
        lcStatus: 'not-required',
        productCost: 260000,
        shippingCost: 12000,
        customsDuty: 0,
        otherCost: 4500,
        currency: 'BDT',
        notes: 'Local fabric and ready-goods supplier.',
        createdAt: shiftDays(-42),
        updatedAt: shiftDays(-3),
      },
    },
    customers: {
      cus_retail: {
        id: 'cus_retail',
        name: 'Nahid Hasan',
        company: 'Retail',
        phone: '+8801900000001',
        location: 'Mirpur, Dhaka',
        due: 0,
        supportStatus: 'none',
        supportNote: 'No active technical support request.',
        isPremium: false,
        createdAt: shiftDays(-45),
        updatedAt: shiftDays(-2),
      },
      cus_corp: {
        id: 'cus_corp',
        name: 'Apex Fashion',
        company: 'Apex Fashion',
        phone: '+8801900000002',
        location: 'Banani, Dhaka',
        due: 18500,
        supportStatus: 'in-progress',
        supportNote: 'POS printer servicing follow-up is scheduled.',
        isPremium: true,
        createdAt: shiftDays(-38),
        updatedAt: shiftDays(-1),
      },
      cus_loyal: {
        id: 'cus_loyal',
        name: 'Shanta Enterprise',
        company: 'Shanta Enterprise',
        phone: '+8801900000003',
        location: 'Agrabad, Chattogram',
        due: 8500,
        supportStatus: 'needed',
        supportNote: 'Requested technical support for barcode scanner setup.',
        isPremium: false,
        createdAt: shiftDays(-30),
        updatedAt: shiftDays(0),
      },
    },
    products: {
      prd_jacket: {
        id: 'prd_jacket',
        name: "Men's Jacket",
        category: 'Outerwear',
        brand: 'Muaz',
        sku: 'MUZ-JKT-001',
        serialNumber: 'SN-JKT-48120',
        warrantyMonths: 6,
        warehouseId: 'wh_dhaka',
        supplierId: 'sup_textile',
        purchasePrice: 1650,
        sellingPrice: 2450,
        wholesalePrice: 2200,
        stockQty: 48,
        minStock: 20,
        maxStock: 120,
        status: 'active',
        description: 'Water-resistant men jacket.',
        createdAt: shiftDays(-40),
        updatedAt: shiftDays(-1),
      },
      prd_punjabi: {
        id: 'prd_punjabi',
        name: 'Premium Punjabi',
        category: 'Ethnic Wear',
        brand: 'Muaz',
        sku: 'MUZ-PNJ-002',
        serialNumber: 'SN-PNJ-18044',
        warrantyMonths: 0,
        warehouseId: 'wh_dhaka',
        supplierId: 'sup_alpha',
        purchasePrice: 950,
        sellingPrice: 1650,
        wholesalePrice: 1450,
        stockQty: 18,
        minStock: 25,
        maxStock: 140,
        status: 'low-stock',
        description: 'Best-selling festive punjabi.',
        createdAt: shiftDays(-32),
        updatedAt: shiftDays(-2),
      },
      prd_tracksuit: {
        id: 'prd_tracksuit',
        name: 'Urban Tracksuit',
        category: 'Sportswear',
        brand: 'Muaz Active',
        sku: 'MUZ-TRK-003',
        serialNumber: 'SN-TRK-90093',
        warrantyMonths: 3,
        warehouseId: 'wh_ctg',
        supplierId: 'sup_globe',
        purchasePrice: 1400,
        sellingPrice: 2250,
        wholesalePrice: 2050,
        stockQty: 9,
        minStock: 15,
        maxStock: 90,
        status: 'low-stock',
        description: 'Two-piece tracksuit set.',
        createdAt: shiftDays(-21),
        updatedAt: shiftDays(-3),
      },
      prd_polo: {
        id: 'prd_polo',
        name: 'Classic Polo',
        category: 'Casual Wear',
        brand: 'Muaz',
        sku: 'MUZ-POL-004',
        serialNumber: 'SN-POL-77281',
        warrantyMonths: 0,
        warehouseId: 'wh_ctg',
        supplierId: 'sup_textile',
        purchasePrice: 550,
        sellingPrice: 980,
        wholesalePrice: 860,
        stockQty: 72,
        minStock: 30,
        maxStock: 160,
        status: 'active',
        description: 'Cotton polo shirt.',
        createdAt: shiftDays(-18),
        updatedAt: shiftDays(-1),
      },
    },
    orders: {
      ord_1001: {
        id: 'ord_1001',
        billNumber: 'INV-1001',
        customerId: 'cus_retail',
        customerName: 'Nahid Hasan',
        salesPersonId: 'u_sales',
        salesPersonName: 'Sabbir Ahmed',
        status: 'pending',
        paymentStatus: 'partial',
        total: 4900,
        paid: 2500,
        due: 2400,
        deliveryDate: shiftDays(1),
        paymentDueDate: shiftDays(15),
        dueReference: 'owner',
        createdAt: shiftDays(0),
        items: [
          {
            productId: 'prd_jacket',
            productName: "Men's Jacket",
            quantity: 2,
            unitPrice: 2450,
            purchasePrice: 1650,
          },
        ],
      },
      ord_1002: {
        id: 'ord_1002',
        billNumber: 'INV-1002',
        customerId: 'cus_corp',
        customerName: 'Apex Fashion',
        salesPersonId: 'u_sales',
        salesPersonName: 'Sabbir Ahmed',
        status: 'ready',
        paymentStatus: 'unpaid',
        total: 6600,
        paid: 0,
        due: 6600,
        deliveryDate: shiftDays(2),
        paymentDueDate: shiftDays(-3),
        dueReference: 'courier',
        overdueNotified: false,
        createdAt: shiftDays(-1),
        items: [
          {
            productId: 'prd_punjabi',
            productName: 'Premium Punjabi',
            quantity: 4,
            unitPrice: 1650,
            purchasePrice: 950,
          },
        ],
      },
      ord_1003: {
        id: 'ord_1003',
        billNumber: 'INV-1003',
        customerId: 'cus_loyal',
        customerName: 'Shanta Enterprise',
        salesPersonId: 'u_admin',
        salesPersonName: 'Rahat Hossain',
        status: 'shipped',
        paymentStatus: 'paid',
        total: 4510,
        paid: 4510,
        due: 0,
        deliveryDate: shiftDays(-1),
        paymentDueDate: shiftDays(11),
        dueReference: '',
        createdAt: shiftDays(-3),
        items: [
          {
            productId: 'prd_polo',
            productName: 'Classic Polo',
            quantity: 5,
            unitPrice: 902,
            purchasePrice: 550,
          },
        ],
      },
    },
    purchases: {
      pur_1001: {
        id: 'pur_1001',
        productId: 'prd_tracksuit',
        productName: 'Urban Tracksuit',
        supplierId: 'sup_globe',
        supplierName: 'Globe Imports',
        quantity: 18,
        unitCost: 1400,
        currency: 'BDT',
        total: 25200,
        status: 'received',
        createdAt: shiftDays(0),
      },
      pur_1002: {
        id: 'pur_1002',
        productId: 'prd_punjabi',
        productName: 'Premium Punjabi',
        supplierId: 'sup_alpha',
        supplierName: 'Alpha Sourcing',
        quantity: 40,
        unitCost: 950,
        currency: 'BDT',
        total: 38000,
        status: 'received',
        createdAt: shiftDays(-5),
      },
    },
    tasks: {
      task_1001: {
        id: 'task_1001',
        title: 'Follow up low stock for Punjabi',
        description: 'Place reorder before weekend campaign starts.',
        module: 'inventory',
        status: 'pending',
        priority: 'high',
        assigneeId: 'u_store',
        assigneeName: 'Farzana Akter',
        dueDate: shiftDays(1),
        createdBy: 'u_admin',
        createdAt: shiftDays(-1),
      },
      task_1002: {
        id: 'task_1002',
        title: 'Collect due from Apex Fashion',
        description: 'Coordinate payment reminder and shipment release.',
        module: 'sales',
        status: 'in-progress',
        priority: 'medium',
        assigneeId: 'u_accounts',
        assigneeName: 'Nabila Islam',
        dueDate: shiftDays(2),
        createdBy: 'u_admin',
        createdAt: shiftDays(0),
      },
      task_1003: {
        id: 'task_1003',
        title: 'Verify jacket rack labels',
        description: 'Confirm warehouse rack codes before dispatch.',
        module: 'warehouse',
        status: 'done',
        priority: 'low',
        assigneeId: 'u_store',
        assigneeName: 'Farzana Akter',
        dueDate: shiftDays(-1),
        createdBy: 'u_admin',
        createdAt: shiftDays(-2),
      },
      task_1004: {
        id: 'task_1004',
        title: 'Check jacket warranty claim',
        description: 'Review the returned jacket and confirm replacement eligibility.',
        module: 'support',
        status: 'in-progress',
        priority: 'high',
        assigneeId: 'u_admin',
        assigneeName: 'Rahat Hossain',
        dueDate: shiftDays(2),
        createdBy: 'u_admin',
        createdAt: shiftDays(0),
      },
    },
    notifications: {
      note_1001: {
        id: 'note_1001',
        title: 'Low stock alert',
        body: 'Premium Punjabi is below the minimum threshold.',
        level: 'warning',
        read: false,
        createdAt: shiftDays(0),
        roles: ['admin', 'store_manager'],
      },
      note_1002: {
        id: 'note_1002',
        title: 'New order created',
        body: 'Order ORD-1001 is waiting for payment confirmation.',
        level: 'info',
        read: false,
        createdAt: shiftDays(0),
        roles: ['admin', 'sales_person', 'accountant'],
      },
      note_1003: {
        id: 'note_1003',
        title: 'Due payment',
        body: 'Apex Fashion has an outstanding invoice balance.',
        level: 'critical',
        read: false,
        createdAt: shiftDays(-1),
        roles: ['admin', 'accountant'],
      },
    },
    activities: {
      act_1001: {
        id: 'act_1001',
        action: 'purchase_received',
        module: 'inventory',
        message: 'Received 18 units of Urban Tracksuit into Chattogram hub.',
        userId: 'u_store',
        userName: 'Farzana Akter',
        createdAt: shiftDays(0),
      },
      act_1002: {
        id: 'act_1002',
        action: 'order_created',
        module: 'sales',
        message: 'Created order ORD-1001 for Nahid Hasan.',
        userId: 'u_sales',
        userName: 'Sabbir Ahmed',
        createdAt: shiftDays(0),
      },
      act_1003: {
        id: 'act_1003',
        action: 'task_updated',
        module: 'operations',
        message: 'Marked rack verification task as done.',
        userId: 'u_store',
        userName: 'Farzana Akter',
        createdAt: shiftDays(-1),
      },
    },
    expenses: {
      exp_1001: {
        id: 'exp_1001',
        category: 'Office Rent',
        amount: 35000,
        note: 'Monthly shop rent for Dhaka showroom.',
        date: shiftDays(-2),
        createdBy: 'u_accounts',
        createdByName: 'Nabila Islam',
        createdAt: shiftDays(-2),
      },
      exp_1002: {
        id: 'exp_1002',
        category: 'Transport',
        amount: 4200,
        note: 'Local delivery van fuel and toll.',
        date: shiftDays(0),
        createdBy: 'u_accounts',
        createdByName: 'Nabila Islam',
        createdAt: shiftDays(0),
      },
    },
    investors: {},
    sellers: {
      sel_kamal: {
        id: 'sel_kamal',
        name: 'Kamal Traders',
        phone: '+8801600000001',
        location: 'Elephant Road, Dhaka',
        notes: 'Sub-dealer for festive collection resale.',
        createdAt: shiftDays(-25),
        updatedAt: shiftDays(-1),
      },
      sel_bristi: {
        id: 'sel_bristi',
        name: 'Bristi Fashion Point',
        phone: '+8801600000002',
        location: 'GEC Circle, Chattogram',
        notes: 'Takes tracksuits on credit, supplies local polo stock.',
        createdAt: shiftDays(-20),
        updatedAt: shiftDays(0),
      },
    },
    sellerTransactions: {
      selt_1001: {
        id: 'selt_1001',
        sellerId: 'sel_kamal',
        sellerName: 'Kamal Traders',
        date: shiftDays(-1),
        productName: "Men's Jacket",
        quantity: 12,
        takenValue: 18000,
        cashGiven: 12000,
        givenValue: 0,
        cashReceived: 0,
        goodsBroughtDescription: '',
        iReceiveAmount: 0,
        theyReceiveAmount: 6000,
        createdAt: shiftDays(-1),
      },
      selt_1002: {
        id: 'selt_1002',
        sellerId: 'sel_bristi',
        sellerName: 'Bristi Fashion Point',
        date: shiftDays(0),
        productName: 'Classic Polo (local stock)',
        quantity: 20,
        takenValue: 9000,
        cashGiven: 0,
        givenValue: 0,
        cashReceived: 0,
        goodsBroughtDescription: '',
        iReceiveAmount: 0,
        theyReceiveAmount: 9000,
        createdAt: shiftDays(0),
      },
      selt_1003: {
        id: 'selt_1003',
        sellerId: 'sel_kamal',
        sellerName: 'Kamal Traders',
        date: shiftDays(0),
        productName: 'Festive Kurta',
        quantity: 15,
        takenValue: 0,
        cashGiven: 0,
        givenValue: 22000,
        cashReceived: 10000,
        goodsBroughtDescription: '',
        iReceiveAmount: 12000,
        theyReceiveAmount: 0,
        createdAt: shiftDays(0),
      },
    },
    couriers: {
      cour_1001: {
        id: 'cour_1001',
        customerId: 'cus_corp',
        customerName: 'Apex Fashion',
        billNumber: 'INV-1002',
        courierName: 'Sundarban Courier',
        productDescription: '4 x Premium Punjabi',
        quantity: 4,
        codAmount: 6600,
        sentDate: shiftDays(-1),
        status: 'in-transit',
        createdAt: shiftDays(-1),
        updatedAt: shiftDays(-1),
      },
      cour_1002: {
        id: 'cour_1002',
        customerId: 'cus_loyal',
        customerName: 'Shanta Enterprise',
        billNumber: 'INV-1003',
        courierName: 'Pathao Courier',
        productDescription: '5 x Classic Polo',
        quantity: 5,
        codAmount: 0,
        sentDate: shiftDays(-3),
        status: 'delivered',
        createdAt: shiftDays(-3),
        updatedAt: shiftDays(-1),
      },
    },
    settings: {
      companyName: 'Muaz Technology',
      currency: 'BDT',
      timezone: 'Asia/Dhaka',
    },
    meta: {
      seededAt,
      version: 'rtdb-demo-v1',
    },
  }
}
